### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by Tarigan0700** [Lukium/palworld-admin#15]
i got connection time out error when using the exe tools

**Comment by Tarigan0700** [comment]
![image](https://github.com/Lukium/palworld-admin/assets/72868704/319913a7-b457-4845-8404-cb772caadc5b)

**Comment by Lukium** [comment]
> ![image](https://private-user-images.githubusercontent.com/72868704/307775042-319913a7-b457-4845-8404-cb772caadc5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDQxNTYsIm5iZiI6MTcwOTA0Mzg1NiwicGF0aCI6Ii83Mjg2ODcwNC8zMDc3NzUwNDItMzE5OTEzYTctYjQ1Ny00ODQ1LTg0MDQtY2I3NzJjYWFkYzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE0MjQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Y2M0MTllOGQyYWY4ZmMwNzMwMzE4ODk0MDQ5OTgyMmViOTIyOWJmYTk4YmQ0NDY2MDYxZjZiOTU0MjJjY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yUywYqCWsPUo6C5by3K5MqyW6LhUc_OOSDXWhz30V60)

Looks like you're trying to run Palworld ADMIN from the directory where PalServer is in. This is incorrect, please follow the install instructions in the readme

**Comment by Lukium** [comment]
Closing since no reply
