### ISSUE TITLE
WorldOption.sav Not Work

### ISSUE THREAD

**Issue by AaronYu0625** [Lukium/palworld-admin#17]
After modifying the "DeathPenalty" to "None" in the Server Settings and saving it, the changes do not take effect. Players still drop all items and pal upon death.

**Comment by insanebugbear** [comment]
I was having this problem too, and I think this latest update changed the values in the config for this server setting. 0 appears to be no death drops, and 3 is drop everything. I manually edited my server setting ini and it seemed to fix the problem, maybe a fix won't be difficult.

**Comment by Lukium** [comment]
Thanks for the info, will change it from using words to using numbers on next update

**Comment by Lukium** [comment]
Implemented on 0.8.6
