### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by VoidPollo** [Lukium/palworld-admin#4]
So firstly, I can't get it to work, after I click "Install | Update" and it finishes, the server comes up briefly and it closes, and the program claims "the server installed successfully!"

But every option is disabled, except to install again, and the backup one and that one says failed to backup.
Once I change to any tab and back the little images and text that used to say SteamCMD IO etc are gone.

After closing and opening the program, still same issue.
If i delete steamcmd and open the program its back to normal but using the install button just does the same thing as above.

---

Dragging the mouse makes the whole program move, which affects the ability to select text with mouse

---

Although false positives its pretty high: https://www.virustotal.com/gui/file/e24e3245729fdd60a5d4d02f7caa775f404b5f3b96c1c006a44e2fba80082240

And at one point I couldnt even get it to open while I had PortMaster running, it was pinging a bunch of things? but all of that above was tested with PortMaster not running at all.

~~

Running Windows 11, up to date. Used the released .exe

**Comment by Lukium** [comment]
> So firstly, I can't get it to work, after I click "Install | Update" and it finishes, the server comes up briefly and it closes, and the program claims "the server installed successfully!"
> 
> But every option is disabled, except to install again, and the backup one and that one says failed to backup. Once I change to any tab and back the little images and text that used to say SteamCMD IO etc are gone.
> 
> After closing and opening the program, still same issue. If i delete steamcmd and open the program its back to normal but using the install button just does the same thing as above.
> 
> Dragging the mouse makes the whole program move, which affects the ability to select text with mouse
> 
> Although false positives its pretty high: https://www.virustotal.com/gui/file/e24e3245729fdd60a5d4d02f7caa775f404b5f3b96c1c006a44e2fba80082240
> 
> And at one point I couldnt even get it to open while I had PortMaster running, it was pinging a bunch of things? but all of that above was tested with PortMaster not running at all.
> 
> ~~
> 
> Running Windows 11, up to date. Used the released .exe

I believe you were testing while I was mid-release. The app pulls the most current UI from my server, and I believe you were pulling the updated UI while running the un-updated backend. Please try again.

As for dragging with the mouse, it's something I'm working on (already fixed on the RCON window)

As for the false positives, it's a result of packaging the code into .exe using pyinstaller (Unfortunately as with any packager, it has been used many times for malicious code, so several antiviruses auto-flag it)

If it's any consolation, I've been submitting new releases to Microsoft to get it pulled from their detection and so far, it has passed every time (just submitted the newest version, still waiting on their analysis).
![image](https://github.com/Lukium/palworld-servertools/assets/99280463/28f1cead-fb3f-4098-878c-e3eca4edc4c7)

**Comment by Lukium** [comment]
Going to close this as we are now down to 1-2 AV hits with all the main ones now marking the app as safe now that I've moved from pyinstaller to nuitka
