### ISSUE TITLE
Save Rcon Data

### ISSUE THREAD

**Issue by BloodDragon2580** [Lukium/palworld-admin#7]
Make to save your RCON connection, like favorite.

**Comment by Lukium** [comment]
> Make to save your RCON connection, like favorite.

Planning an update for later today that will store that last successful launch options and RCON connection information, and reload them on next launch. A way to store "profiles"/"favorites" will come later

**Comment by BloodDragon2580** [comment]
cool thx for the information

**Comment by Lukium** [comment]
> cool thx for the information

Implemented on 0.7.2
