### ISSUE TITLE
Issue when trying to launch pal-admin.exe

### ISSUE THREAD

**Issue by miakx** [Lukium/palworld-admin#8]
This issue occurs when trying to launch the pal-admin.exe

![image_2024-02-14_160837792](https://github.com/Lukium/palworld-admin/assets/36602197/ab30d46f-948b-4bb8-b217-2e86ae0f2d2e)

**Comment by Lukium** [comment]
There was an issue with the original release of 0.7.0. It has been fixed since with re-compiled binaries on the release. Closing the issue as resolved
