### ISSUE TITLE
[Options] [UI/UX] => ServerInjector

### ISSUE THREAD

**Issue by GhastNier** [Lukium/palworld-admin#9]
Reasoning : 
At the moment, we have to use the ServerInjector.exe to launch our servers if we want to be able to insert some mods, it would be great to have an option that let us select between the possible EXE boot file.

Also, having an option to clear the cache would be epic following train of tough

**Comment by Lukium** [comment]
> Reasoning : At the moment, we have to use the ServerInjector.exe to launch our servers if we want to be able to insert some mods, it would be great to have an option that let us select between the possible EXE boot file.
> 
> Also, having an option to clear the cache would be epic following train of tough

Tell me more about the way the server is launched with ServerInjector.exe? Does it need to be passed with any arguments? Does it just need to be launched from the same directory that PalServer.exe? What if you want to pass EpicApp=PalServer and other command line arguments?

If I can understand the full logic and ways of running this, I should be able to implement this relatively easily.

**Comment by Lukium** [comment]
Also, according to a comment on Palworld ADMIN on Nexus Mods, ServerInjector.exe is no longer needed with latest version of UE4SS, have you tried that?
